name: frontend
description: "Everything App - Family financial management platform for tracking expenses, managing budgets, and achieving financial goals together."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Icons & Design
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.0

  # Navigation
  go_router: ^14.0.0

  # Network & API
  dio: ^5.4.0

  # Data Classes & Serialization
  freezed_annotation: ^2.4.0
  json_annotation: ^4.9.0

  # Storage
  flutter_secure_storage: ^9.2.0
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.19.0
  flutter_dotenv: ^5.2.0
  collection: ^1.18.0
  uuid: ^4.5.0

  # UI Enhancements
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0

  # Platform
  shared_preferences: ^2.3.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.3.0

  # Code Generation
  build_runner: ^2.4.0
  freezed: ^2.5.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

  # Testing
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

  # Utilities
  yaml: ^3.1.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.example

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  # Example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic